steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  # Change $COMMIT_SHA to 'latest'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudrun-go-api:latest', '.']

# 2. Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  # Change $COMMIT_SHA to 'latest'
  args: ['push', 'gcr.io/$PROJECT_ID/cloudrun-go-api:latest']

# 3. Deploy the container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'run',
      'deploy',
      'cloudrun-go-api',
      # Change $COMMIT_SHA to 'latest'
      '--image', 'gcr.io/$PROJECT_ID/cloudrun-go-api:latest',
      '--platform', 'managed',
      # ... (rest of the args)
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', '${_INSTANCE_CONNECTION_NAME}',
      '--set-env-vars', 'DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},PORT=8080'
  ]
timeout: '1600s'

# Substitutions to be passed to the build command
# These values will need to be provided when running the build.
substitutions:
    _REGION: us-central1
    _INSTANCE_CONNECTION_NAME: curdop7-474215:us-central1:my-mysql
    _DB_USER: root
    _DB_PASS: mahesh
    _DB_NAME: ecommercedb